### ISSUE TITLE
Credits suggestion

### ISSUE THREAD

**Issue by IvanFilipov** [dako98/Introduction-to-Programming--2019-2020#1]
Would you mind giving us ([Vasilena](https://github.com/VasiPeycheva), [Ivan](https://github.com/IvanFilipov), [Plamen](https://github.com/pminev)) some credit for the containing of this repository? Cause, from what I am seeing, it is actually a _mirrored_ version of ours old [repo](https://github.com/VasiPeycheva/Introduction-to-Programming--2017-2020/tree/6dc6d76e933e0dae05f0c6a12399ccc3d855c29b).

Please, take into consideration, that the proper way of _modifying/improving_ someone else's **open source project** is by _**forking**_ it. That's how the origin can be kept and still the improvements can be done by another author.

All the best,
**VIP** team

**Comment by dimbata23** [comment]
Of course! The **VIP** team deserves *credit* for the work, and *adjustments* have been made accordingly. **Thank you** for the amazing teaching experience and the information!

Sincerely yours,
Alexander and Dako
